version: '3.7'
services:
  postgres_service:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

